### ISSUE TITLE
exercises.slice is not a function

### ISSUE THREAD

**Issue by DEADHEAD652** [adrianhajdin/project_fitness_app#29]
i am getting the following error and my api is working 

> exercises.slice is not a function
TypeError: exercises.slice is not a function
    at Exercises (http://localhost:3000/main.9ca945adc80ee5b1342b.hot-update.js:59:38)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:48253:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:51135:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:52847:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:37845:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:37889:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:37946:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:57820:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:57067:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:56990:9)

**Comment by Ibra-22Kh** [comment]
I think you have used all of your rapidAPI requests, to fix this you can log in with another account and change you local ip address
Hope this help.
