### ISSUE TITLE
Exercises.slice is not a function

### ISSUE THREAD

**Issue by MikeMarsha11** [adrianhajdin/project_fitness_app#32]
I have seen other peope have the same issue:
I am a new user to rapidAPI, so I don't believe the issue is that I have run out of requests.
However, I did make a new account and change local IP to get a different key as suggested and still get the error. I do not know where to go from here. I have the rest of the project completed.
below is the error I recieve:

ERROR
exercises.slice is not a function
TypeError: exercises.slice is not a function
    at Exercises (http://localhost:3000/main.0eff7a31ea01d5c8367a.hot-update.js:61:38)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:49655:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:52537:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:54249:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:39247:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:39291:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:39348:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:59222:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:58469:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:58392:9)

**Comment by infinite1400** [comment]
exercises.slice is not a function is due to the fact that useEffect in Exercises.js is populating the exercises state but in the mean time it goes further and sees exercises.slice function and the exercise is not yet populated and slice function is working the exercise variable i did that after the useEffect i put a conditional statement that it exercise.length==0 then in mean time load a infinity component and after it is populated with data then go further and see exercises.slice function.
Atteching a ScreenShot for further clearification.
![Uploading Screenshot (1211).png…]()

**Comment by Doobiii** [comment]
`const currentExercises = Array.isArray(exercises) ? exercises.slice(
    indexOfFirstExercise,
    indexOfLastExercise
  ) : [];`
  
  use this.. it will solve the problem

**Comment by akshat05ag** [comment]
const currentExercises = Array.isArray(exercises) ? exercises.slice( indexOfFirstExercise, indexOfLastExercise ) : []; 
using this u can resolve your error and the code will run fine.
