### ISSUE TITLE
exercises.slice is not a function

### ISSUE THREAD

**Issue by PtSik** [adrianhajdin/project_fitness_app#37]
when i click on the body part i get this error

tried to create new account on the rapidApi but still facing same issue.

exercises.slice is not a function
TypeError: exercises.slice is not a function
    at Exercises (http://localhost:3000/static/js/bundle.js:428:38)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:47733:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:50615:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:52327:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:37325:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:37369:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:37426:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:57300:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:56547:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:56470:9)

**Comment by PtSik** [comment]
OKay i fixed it by deleting ?limit=900 in fetchData but now i get only 10 items, how can i get everything? 

 if (bodyPart === 'all') {
        exercisesData = await fetchData('https://exercisedb.p.rapidapi.com/exercises?limit=900', exerciseOptions);
      } else {
        exercisesData = await fetchData(`https://exercisedb.p.rapidapi.com/exercises/bodyPart/${bodyPart}`, exerciseOptions);
      }

**Comment by infinite1400** [comment]
exercises.slice is not a function is due to the fact that useEffect in Exercises.js is populating the exercises state but in the mean time it goes further and sees exercises.slice function and the exercise is not yet populated and slice function is working the exercise variable i did that after the useEffect i put a conditional statement that it exercise.length==0 then in mean time load a <Loader/> infinity component and after it is populated with data then go further and see exercises.slice function. 
Atteching a ScreenShot for further clearification.
![image](https://github.com/adrianhajdin/project_fitness_app/assets/112894392/597c4e54-e25c-4b4e-9424-1cb9ffe86b0f)
 This way you can get everything not only 10 items
